version: '3'

services:
  vegeta:
    build: .
    volumes:
      - ./results:/results
    depends_on:
      - prometheus
      - grafana
    ports:
      - "8000:8000"
    networks:
      - vegeta-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../grafana/provisioning/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - vegeta-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ../grafana/provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ../grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"
    networks:
      - vegeta-net

networks:
  vegeta-net: